#!/bin/bash

# ========================================
# 🚀 COMANDOS RÁPIDOS PARA DEPLOY - NexuZap
# ========================================

echo "📋 INSTRUÇÕES DE DEPLOY"
echo ""
echo "════════════════════════════════════════"
echo "  1️⃣  PUSH NO GITHUB (no seu computador)"
echo "════════════════════════════════════════"
echo ""
echo "cd /caminho/para/nexuzap"
echo "git add ."
echo "git commit -m \"fix: corrige sincronização de grupos\""
echo "git push origin main"
echo ""
echo "════════════════════════════════════════"
echo "  2️⃣  ATUALIZAR NA VPS (executar na VPS)"
echo "════════════════════════════════════════"
echo ""
echo "cd /opt/nexuzap"
echo "sudo ./update_vps.sh"
echo ""
echo "════════════════════════════════════════"
echo "  ✅  PRONTO!"
echo "════════════════════════════════════════"
echo ""
echo "Acesse: https://nexuzap.com"
echo "Teste: Conexões → Sincronizar Grupos"
echo ""
echo "════════════════════════════════════════"
echo "  📊  COMANDOS ÚTEIS"
echo "════════════════════════════════════════"
echo ""
echo "# Ver logs do WhatsApp Service:"
echo "sudo tail -n 50 /var/log/supervisor/nexuzap-whatsapp.out.log"
echo ""
echo "# Ver status dos serviços:"
echo "sudo supervisorctl status"
echo ""
echo "# Reiniciar serviço WhatsApp:"
echo "sudo supervisorctl restart nexuzap-whatsapp"
echo ""
echo "# Backup do MongoDB:"
echo "sudo ./backup.sh"
echo ""
echo "# Restaurar backup:"
echo "sudo ./restore.sh"
echo ""
